---
- name: Install Apache on Ubuntu
  ansible.builtin.apt:
    name: apache2
    state: present

- name: Copy Apache index.html
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: "0644"

- name: Restart Apache to apply changes
  ansible.builtin.service:
    name: apache2
    state: restarted
