apiVersion: v1
kind: Service
metadata:
  name: simple-web-app-service
  namespace: sre-challenge
spec:
  selector:
    app: simple-web # Selects pods with label app=simple-web to forward traffic to ports
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
