apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: simple-web-app-hpa
  namespace: sre-challenge
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-web-app #targets the simple-web-app deployment
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
