- name: Apply common setup on all servers
  hosts: all
  become: true
  roles:
    - common

- name: Configure Apache on Ubuntu
  hosts: ubuntu
  become: true
  roles:
    - apache

- name: Configure MariaDB on RedHat
  hosts: redhat
  become: true
  roles:
    - mariadb
