name: Kubernetes Lint

on:
  push:
    paths:
      - 'k8s/**.yaml'
      - 'k8s/**.yml'
  pull_request:
    paths:
      - 'k8s/**.yaml'
      - 'k8s/**.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Kubeval linter inside Docker container on each manifest
      run: |
        for file in k8s/*.yaml; do
          echo "Linting $file"
          docker run --rm -v "${{ github.workspace }}/k8s":/k8s garethr/kubeval "/k8s/$(basename $file)"
        done
