name: Kubernetes Lint

on:
  push:
    paths:
      - 'k8s/**.yaml'
      - 'k8s/**.yml'
  pull_request:
    paths:
      - 'k8s/**.yaml'
      - 'k8s/**.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run kube-linter on k8s manifests
      uses: stackrox/kube-linter-action@v0.4.4
      with:
        args: ./k8s